### ISSUE TITLE
Does  not work at all for me - Mac server

### ISSUE THREAD

**Issue by dadrepus** [contrary-cat/LocalTVExtras.bundle#2] opened 2019-03-11 03:33 UTC
Installed correctly in Plugins folder, show up in Agents. Folders correctly named, files correctly named.
Nothing show up in web or any client. did i forget to do something?

**Comment by contrary-cat** [comment] 2019-03-16 20:51
Could you please refresh metadata on the TV show you're trying to update with Extras, and then send me the file: `~/Library/Logs/Plex Media Server/PMS Plugins/com.plexapp.agents.localtvextras.log`

If the Library folder isn't visible in your home folder, then open the home folder in Finder, hit cmd+J and you will see a "Show Library Folder" option which you can enable

**Comment by dadrepus** [comment] 2019-03-17 14:44
Did you get the file? I just replied to your email instead of using this form?
[com.plexapp.agents.localmedia.log](https://github.com/contrary-cat/LocalTVExtras.bundle/files/2975285/com.plexapp.agents.localmedia.log)

But here it is again.

**Comment by contrary-cat** [comment] 2019-03-17 16:23
That's actually the localmedia log file (the official Plex one), there should be one called `com.plexapp.agents.localtvextras.log` in the same folder that contains the logs from this agent.

I got a notification email when you posted this comment, but I didn't get anything earlier, so I suspect replying to the emails doesn't work.

**Comment by dadrepus** [comment] 2019-03-17 16:52
[com.plexapp.agents.localtvextras.log](https://github.com/contrary-cat/LocalTVExtras.bundle/files/2975437/com.plexapp.agents.localtvextras.log)

Right  one?

**Comment by contrary-cat** [comment] 2019-03-17 17:24
Yes that's the right one. The log tells me that there aren't any errors in the code - the agent just isn't finding any extras for some reason. Could you give me an example of your folder structure for one TV Show including the episode file names and where the extras are located and how they are named?

**Comment by dadrepus** [comment] 2019-03-17 18:01
![Screen Shot 2019-03-17 at 1 59 34 PM](https://user-images.githubusercontent.com/22350089/54495750-1df31700-48bd-11e9-9ac2-fb0cddc2df25.png)
![Screen Shot 2019-03-17 at 1 58 53 PM](https://user-images.githubusercontent.com/22350089/54495752-221f3480-48bd-11e9-8ed6-a002326d027f.png)
![Screen Shot 2019-03-17 at 1 58 01 PM](https://user-images.githubusercontent.com/22350089/54495755-29464280-48bd-11e9-9127-609707741e37.png)

**Comment by dadrepus** [comment] 2019-03-17 18:11
this is what I am getting now after a relink to the server.  This is better than I have ever gotten before and I have had the plugin install for several days.
![Screen Shot 2019-03-17 at 2 08 17 PM](https://user-images.githubusercontent.com/22350089/54495865-7d055b80-48be-11e9-891a-5e8371ff567f.png)

**Comment by dadrepus** [comment] 2019-03-17 18:17
still nothing for stargate.
![Screen Shot 2019-03-17 at 2 16 32 PM](https://user-images.githubusercontent.com/22350089/54495936-627fb200-48bf-11e9-9096-cb4e9dd20a86.png)

**Comment by contrary-cat** [comment] 2019-03-17 18:39
It does seem to be working properly for Atlantis (except for thumbnails?), which is encouraging. Can you try a metadata refresh on SG-1 only – while you're in the show page, click the … (more) button on the top-right, then "Refresh Metadata".

I don't know if you've changed any of the default settings, but I wanted to quickly note that Plex Web doesn't display extras attached to Seasons or Episodes, only the extras attached at the show level. There are some clients that show them, so for some people it is worth enabling the setting for episode & show extras.

**Comment by dadrepus** [comment] 2019-03-17 23:32
Well, now they are showing up the same as Atlantis without thumbs which I guess is oK for now.
Thanks for working on this plugin. I am an orderly kind of guy and this was driving me crazy.

**Comment by contrary-cat** [comment] 2019-03-19 13:38
Can you tell me whether the videos linked to the extras play properly?

I've seen blank thumbnails before in an earlier version of the agent, where I wasn't handling unicode paths properly, and so Plex wasn't able to reach the video to analyse it.

If you can play the videos, then the problem is something different; but if you can't, then there's probably something PMS doesn't understand in the file path that the agent passes to it.

**Comment by dadrepus** [comment] 2019-03-19 14:46
Videos play properly, just no thumbs.

**Comment by contrary-cat** [comment] 2019-03-23 10:41
I've noticed that blank thumbnails is an issue on Plex Media Server 1.15.2.793 (which I'm running on Mojave), but not Plex Media Server 1.15.0.659 (High Sierra).

I tried adding a test extra to one of my movies, and confirmed that this is also a problem for movie extras using the Plex Local Media agent, so I think there may be a server issue.

There is a workaround if you want to include thumbnails now – if you save an image in the same folder, with the same file name (apart from extension) as an extra, then it will be used as the thumbnail in my agent.

It's a bit cumbersome, because Plex won't update the image unless something else changes; I find the easiest way is to:
1. Disable the Local TV Extras Agent (under Settings > Agents > Shows > whichever top level agent you're using)
2. In another tab, navigate to the show you want to update, and perform a metadata refresh on that show only (this will temporarily remove all extras for the show)
3. Renable the agent
4. Refresh metadata on the show again, and the extra should return complete with image

Renaming the extra file will also prompt Plex to update the information, but that would also be a two-refresh task if you want to keep the original title.

I'll close this issue, since I think the problem is on Plex's end, but if you have any difficulties then let me know.

**Closed as completed by contrary-cat** 2019-03-23 10:41 UTC

**Comment by ghost** [comment] 2019-05-05 13:59
> 
> 
> It does seem to be working properly for Atlantis (except for thumbnails?), which is encouraging. Can you try a metadata refresh on SG-1 only – while you're in the show page, click the … (more) button on the top-right, then "Refresh Metadata".
> 
> I don't know if you've changed any of the default settings, but I wanted to quickly note that Plex Web doesn't display extras attached to Seasons or Episodes, only the extras attached at the show level. There are some clients that show them, so for some people it is worth enabling the setting for episode & show extras.

Sorry to comment on a closed issue, but I wanted to clarify something about your observation. I was able to display the extras at the Show level, but not at the Season level (even though my structure is fully prepared for it). Then I read this comment, and apparently Plex Web is unable to display extras on Show Level, but some other clients are able. Since currently I'm only using Plex Web and Plex iOS (at an iPad, and with this client I can't see extras even at Show level), can you tell me any other client that is able to display at Season level?

**Comment by contrary-cat** [comment] 2019-05-05 14:20
I don't have all these clients myself, so this is mostly a summary of what I have been told on the [thread in the plex forums](https://forums.plex.tv/t/local-tv-extras-agent/226648).

Episodes only:
* iOS client
(not sure why this is, this seems to be the only client that supports TV extras only on episodes)

Show only:
* Plex Media Player
* Plex Web Client

Show and Season:
* Roku Client (reported on [6th January](https://forums.plex.tv/t/local-tv-extras-agent/226648/62), hopefully the recent updates haven't changed this)
* Kodi with the [official Plex Add-on](https://kodi.tv/addon/scripts-video-add-ons/plex)
 (This also includes MRMC with the same Plex Add-on, which is a tolerable experience on AppleTV, but not good on iOS in my opinion)

Show, Season and Episode:
* The Android client (I believe that this includes Android TV/NVIDIA Shield as well as Android Phones & Tablets)

No TV Extras:
* The Apple TV client

The ones I can personally confirm are Plex Web (naturally), Plex Media Player, Plex for Kodi, iOS and Apple TV.

The quickest way to see your season extras would probably be to download Kodi and install the Plex for Kodi add-on.

**Comment by ghost** [comment] 2019-05-05 15:01
Thank you for the quick and thorough response. I'm currently considering getting an Android TV device, so maybe I'll give it a shot on Season extras, but for now, Show extras it is.

Since this feature already exists "natively" for Movies, I think Plex developers should also implement this for TV Shows. But still, great work man, and thanks for sharing the plugin with us.

**Comment by dadrepus** [comment] 2019-05-05 16:38
So, as per your advice, I got some images from TVDB and added them to the folder that housed my extras, Named them exactly as the mp4's were named. Refreshed with your plug-in off and once again with your plug-in on. No thumbs created for the extras. Example: Stargate-Continuum.mp4 and Stargate-Continuum.jpg. Any clues?

**Comment by contrary-cat** [comment] 2019-05-05 16:59
Did the extras disappear when you refreshed with the agent turned off? (It only works if they are completely removed from the database before adding the thumbnail)
  

  
An alternative method is to slightly rename the extra you are testing. E.g. change both Stargate-Continuum mp4 and jpg to Stargate_Continuum or Stargate Continuum, then refresh metadata    The file should then be treated as a brand new extra and the thumbnail properly linked.   
  
  

  
>

**Comment by dadrepus** [comment] 2019-05-05 17:33
Turning off your plugin and then refreshing the metadata did not remove the extras, renaming both the mp4 and jpg and refreshing data did indeed give me images. But turning off and back on the plugin did nothing.
![Screen Shot 2019-05-05 at 1 22 35 PM](https://user-images.githubusercontent.com/22350089/57197821-d80c1400-6f39-11e9-9e46-b4a62c41fd2e.png)
Unfortunately the did not take on the shape of a normal thumb, just a partial. you can see I added "-extra" to the end of each.
Liveable

**Comment by contrary-cat** [comment] 2019-05-05 17:57
Yes, extra thumbnails are all in 16:9 aspect ratio in Plex.

If you'd prefer poster thumbnails, then I would recommend including all three in your movie library and using collections:
![Stargate Collection](https://user-images.githubusercontent.com/45716135/57198012-ebcd6f80-6f65-11e9-8c03-9605c03a1a26.png)

There's a Plex support page on collections [here](https://support.plex.tv/articles/201273953-collections/). If the exact same name (I used "Stargate") is used for your collections in each library, then they will be linked, and you'll see related movies as well as TV shows. I only have the original movie, but if the three you have here are all added to a Stargate collection, as well as the show, then they will all be displayed there.

The "Collection Inline library display options" section on the support page is quite useful if you don't want all your collections to show up in the main view of the libraries.
